### ISSUE TITLE
Error: Unable to resolve module stream (cheerio-without-node-native)

### ISSUE THREAD

**Issue by pnthach95** [gaetanozappi/react-native-gfycat-resolve#1]
- [x] Review the documentation: https://github.com/gaetanozappi/react-native-gfycat-export
  - [x] Search for existing issues (including closed issues): https://github.com/gaetanozappi/react-native-gfycat-export/issues

## Environment
```
react@16.8.3
react-native@0.59.9
react-native-gfycat-export@0.0.1
```

## Description
`cheerio-without-node-native@1.0.0-rc.2` caused `Error: Unable to resolve module stream from .../node_modules/cheerio-without-node-native/node_modules/parse5/lib/parser/parser_stream.js`

I tried `0.20.2`, it fixed the error ([cheerio-without-node-native/#1](https://github.com/oyyd/cheerio-without-node-native/issues/1#issuecomment-459592814)).

## Reproducible Demo
```
const gif = 'https://gfycat.com/presentpleasedcaecilian-baseball-atlanta-braves';
GfResolve(gif)
	.then((r) => { this.setState({ url: r }); })
    .catch((error) => {
    	console.error('Error:', error);
    });
```

**Comment by gaetanozappi** [comment]
Hi @pnthach95 :  Strange, I tried it on snack.expo.io, problems didn't give me.
Is the problem solved by changing the version?

**Comment by pnthach95** [comment]
Yes. And they want users to use old version, like they said on [this latest commit.](https://github.com/oyyd/cheerio-without-node-native/commit/cb87b388e29b9a41baffb4801fc4744f7332a7b3)

**Comment by gaetanozappi** [comment]
@pnthach95 : Ok, thx I did update let me know.
